version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
            #- "4430:443"
        volumes:
            #- ./www:/var/www/html/
            - ${DOCUMENT_ROOT-./www}:/var/www/html
            - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
            #- ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
            - ${LOG_DIR-./logs/apache2}:/var/log/apache2
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
            #- ${MYSQL_DATA_DIR-./data}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
